---
Name: tinymce4
---
LeftAndMain:
  extensions:
    - LeftAndMainTinyExtension

SiteTree:
  extensions:
    ['SiteTreeTinyExtension']

HtmlEditorField_Toolbar:
  extensions:
    - HTMLEditorToolbarExtension